### ISSUE TITLE
Move bem preset out of core

### ISSUE THREAD

**Issue by zxqfox** [bem/html-differ#118]
https://github.com/bem/html-differ/blob/master/lib/utils/defaults.js#L16

It should be moved to separate `preset/bem.json` or something.

Ref: https://github.com/enb-bem/enb-bem-tmpl-specs/issues/54

**Comment by eGavr** [comment]
It is a really good idea and I absolutely agree with you,  but it can not be solve in `v1.x.x`,  because it will break the backward compatibility.

Now the CLI is:

```
html-differ file.html file.html --bem
```

and according to this issue it should be

```
html-differ file.html file.html --preset=PRESET_NAME
```

(we should add option 'preset' and remove option `bem`).

I will do this task when there will be more than one presets which are really used,  so we will have serious reason to move `bem` preset out of core.

The task about https://github.com/enb-bem/enb-bem-tmpl-specs/issues/54 can be solved in `enb-bem-tmpl-specs` without doing nothing in `html-differ`, because [here](https://github.com/enb-bem/enb-bem-tmpl-specs/issues/54) enb-bem-tmpl-specs uses strictly `bem` preset and does not provide any abilities to change this options.

**Comment by zxqfox** [comment]
We can make it and leave `--bem` flag as legacy alternative to `--preset=bem`. I don't see this a real problem ;-)

**Comment by eGavr** [comment]
And declare the option `bem` deprecated and support this thing until the major release ( 

I wanner to say that there are no any functional problems with `html-differ`, we just should make `enb-bem-tmpl-specs` provide the ability to set options for `html-differ`

**Comment by zxqfox** [comment]
Да я понимаю, что можно передать объект, и все будет работать, но тогда придется дублировать там весь bem пресет для `html-differ` и будет рассинхрон. ;-) Можно просто унести в отдельный файл bem.json пачку этих настроек.

**Comment by eGavr** [comment]
> Nope, because I can't pass there `{preset: 'bem', option: 1}`.

Не совсем понял как и где это должно работать?
Ты хочешь заюзать пресет и сразу же его переопределить?

**Comment by zxqfox** [comment]
> Ты хочешь заюзать пресет и сразу же его переопределить?

Доопределить :-) Исходя из того, что пресеты должны меняться только в минорных/мажорных версиях (для стабильности), это будет работать ок, и не будет дублирования, но будет возможность гибкого определения. Мы это проходили как в бэм библиотеках, так и в jscs.

**Comment by eGavr** [comment]
Ну то есть ты предлагаешь два варианта исеользования

```js
var htmlDiffer = new HtmlDiffer('bem')
```

и

```js
var htmlDiffer = new HtmlDiffer({ preset: 'bem', redefinedOption: false })
```

??

**Comment by zxqfox** [comment]
Ну да, `preset` использовать просто как базовый набор, подмену значений опций по умолчанию.

Думаешь, плохо будет?

**Comment by eGavr** [comment]
Ну тогда придется поддерживать 3 варианта определения конструктора:
1. передачу всех нужных опций как есть обычным объектом
2. передачу чистого пресета в виде строки
3. передачу объекта,  который переопределяет один из пресетов.

**Comment by zxqfox** [comment]
Я думаю, что (1) и (3) это одно и то же, а (2) сводится к (3), т.е. тоже то же самое:
```js
function (opts) {
  // (2)
  if (typeof opts === 'string') {
    opts = { preset: opts };
  }
  // (3)
  if (opts.preset) {
    var preset = opts.preset;
    delete opts.preset;
    opts = _.assign({}, PRESETS[preset], opts);
  }

  // (2) ... already done.

  // etc.
  // ...
}
```

**Comment by eGavr** [comment]
:+1:  мне нравится)

**Comment by zxqfox** [comment]
Ща PR сделаю
